//! Panel vocabulary for API v3 plugins.
//!
//! Panels are host-rendered abstract widgets declared by a v3 plugin. The plugin
//! defines a [`PanelDef`] and updates widgets via [`PluginAsync::PanelUpdate`];
//! the host forwards user actions back as [`HostAsync::PanelEvent`].

use serde::{Deserialize, Serialize};

use crate::ribbon::owned::OwnedIconKind;

pub mod floating;

/// Where the host should place a panel relative to the main window.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DockZone {
    /// Free-floating overlay inside the main window.
    Floating,
    /// Docked to the left edge (legacy sidebar behaviour).
    Left,
    /// Docked to the right edge.
    Right,
}

impl Default for DockZone {
    fn default() -> Self {
        DockZone::Floating
    }
}

/// How multiple panels in the same dock zone should be presented.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DockStyle {
    /// Stacked on top of each other.
    Stack,
    /// Rendered as tabs.
    Tabs,
}

impl Default for DockStyle {
    fn default() -> Self {
        DockStyle::Tabs
    }
}

/// Declaration of a panel a plugin can open.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PanelDef {
    pub id: String,
    pub title: String,
    pub icon: Option<OwnedIconKind>,
    // NEW: geometry / docking hints for floating panels.
    pub dock: DockZone,
    pub initial_x: Option<f32>,
    pub initial_y: Option<f32>,
    pub initial_width: f32,
    pub initial_height: f32,
    pub min_width: f32,
    pub min_height: f32,
    /// Zones this panel is allowed to dock to. If the requested zone is not
    /// listed, the panel falls back to `DockZone::Floating` (or the first
    /// allowed zone if floating is also disallowed). An empty vector means no
    /// docking changes are allowed; the panel will stay in its initial zone.
    pub dockable_zones: Vec<DockZone>,
    /// Whether the user is allowed to drag this panel out of a dock zone.
    pub allow_undock: bool,
    /// Whether the user is allowed to resize this panel.
    pub resizable: bool,
    /// Whether the user is allowed to drag this panel.
    pub draggable: bool,
    /// How to render this panel when it shares a dock zone with others.
    pub dock_style: DockStyle,
}

impl Default for PanelDef {
    fn default() -> Self {
        Self {
            id: String::new(),
            title: String::new(),
            icon: None,
            dock: DockZone::default(),
            initial_x: None,
            initial_y: None,
            initial_width: 260.0,
            initial_height: 400.0,
            min_width: 160.0,
            min_height: 120.0,
            dockable_zones: vec![DockZone::Floating, DockZone::Left, DockZone::Right],
            allow_undock: true,
            resizable: true,
            draggable: true,
            dock_style: DockStyle::default(),
        }
    }
}

/// Opaque handle to an open panel. Allocated by the host.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PanelHandle(pub u64);

/// Abstract widget inside a plugin panel.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Widget {
    Label(String),
    Button { id: String, label: String },
    TextInput { id: String, value: String },
    MultilineOutput { id: String, lines: Vec<String> },
    List { id: String, items: Vec<String> },
}

/// Event generated by user interaction with a host-rendered panel.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum PanelEvent {
    Clicked(String),
    TextChanged { id: String, value: String },
    ItemSelected { id: String, index: usize },
    Closed,
    // NEW: floating-panel lifecycle events.
    Moved { x: f32, y: f32 },
    Resized { width: f32, height: f32 },
    Focused,
    Docked { zone: DockZone },
    Undocked,
}

/// Errors returned by the host panel surface.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PanelError {
    Unsupported,
    UnknownHandle,
    Io(String),
    NotImplemented,
}

impl std::fmt::Display for PanelError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PanelError::Unsupported => write!(f, "panels not supported"),
            PanelError::UnknownHandle => write!(f, "unknown panel handle"),
            PanelError::Io(s) => write!(f, "panel io error: {s}"),
            PanelError::NotImplemented => write!(f, "panel operation not implemented"),
        }
    }
}

impl std::error::Error for PanelError {}
